---
title: "PTBP1_counts"
author: "KN"
date: "2023-10-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/home/kate/Genomics_UA/my_data_sets/PTB/")
```

```{r}
library(tidyverse)
library(org.Mm.eg.db)
library(biomaRt)
library(tximport)
```


```{r}

#upload metadata and count_table
metadata_table <- read.csv("ptb_metadata_table.csv")
counts_tsv <- "./counts.tsv"
if (file.exists(counts_tsv)){
    counts <- read_tsv(counts_tsv) %>% column_to_rownames("ensembl_gene_id")
}else{
    files <- fs::dir_ls(path = "./geo_inp", glob = "*quant.sf.txt")
    counts <- readr::read_tsv(files, id = "path", col_names = T, col_select = c("Name", "NumReads"))
    colnames(counts)<-c("path","ensembl_gene_id", "raw_counts")
    df_split <- str_split_fixed(counts$path, "_", 3) %>% as.data.frame()
    counts$sample <- df_split$V2 
    counts <- counts %>% 
        mutate(sample = str_replace(sample, "inp/", "")) %>% 
        dplyr::relocate(sample) %>% dplyr::select(-path) %>% 
        pivot_wider(names_from = "sample", values_from = "raw_counts")
    write.table(counts, counts_tsv, sep="\t", row.names = F)   
}

#remove low counts from analysis and rownames_to_column
counts <- counts[which(rowSums(counts)>10),]%>% rownames_to_column("ensembl_transcript_id")

#checking if unique
counts %>%unique() 
```


```{r}
#remove info after dot (remove version of transcropt ID)
counts$ensembl_transcript_id <- gsub("\\.\\d+$", "", counts$ensembl_transcript_id)
keytypes(org.Mm.eg.db)

#mapped_id <- mapIds(org.Mm.eg.db, counts$ensembl_transcript_id, "SYMBOL", "ENSEMBLTRANS")
#mapped_id <- mapped_id %>% as.data.frame()%>%  tibble::rownames_to_column("ensembl_transcript_id") %>%   rename(SYMBOL = ".")

mart <- useMart("ensembl", dataset = "mmusculus_gene_ensembl")
atr <- listAttributes(mart)
listDatasets(mart)
?useMart

biomart_list <- getBM(filter="ensembl_transcript_id",
                      attributes = c("ensembl_transcript_id", "hgnc_trans_name", "transcript_biotype",
                                     "description"),
                      values = counts$ensembl_transcript_id, mart = mart)



select(org.Mm.eg.db, keys= keys(org.Mm.eg.db, keytype="ENSEMBL") , columns=c("SYMBOL","ENSEMBLTRANS"), keytype="ENSEMBL")
```

```{r}


#tx2gene <- getBM(attributes = c("ensembl_transcript_id", "ensembl_gene_id"), mart = mart)

#count_matrix_t <- read.table("./counts.tsv", header = TRUE, row.names = 1)

#gene_counts <- summarizeToGene(count_matrix, tx2gene = tx2gene, ignoreTxVersion = TRUE)

#gene_counts <- count_matrix %>% group_by(ensembl_transcript_id) %>%  summarise(across(everything(), sum))

unique(count_matrix)
```





```{r, eval = TRUE}
save(list = ls(all.names = TRUE), file = "./count_table_prep.RData", envir = environment())


```
